apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: 807801079910.dkr.ecr.eu-central-1.amazonaws.com/hello-world:latest
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
# The port that the container is running on in the cluster

---

apiVersion: v1
kind: Service
metadata:
  name: hello-worldsvc
spec:
  selector:
    app: hello-world
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
