apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: hello-world
  labels:
    application: "DockerDemo"
    tier: "backend"
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: 807801079910.dkr.ecr.eu-central-1.amazonaws.com/hello-world:latest
        # Image that will be used to containers in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: "512Mi"
          requests:
            cpu: 20m
            memory: "128Mi"
      imagePullSecrets:
      - name: ecr-credentials

