apiVersion: v1
kind: Service
metadata:
  name: hello-world
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
  labels:
    app: hello-world
    scrape-service-metrics: 'true'
spec:
  selector:
    app: hello-world
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: web